package md.leonis.soap.cxf;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-18T17:10:11.172+03:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "HelloWorldWSService",
                  wsdlLocation = "classpath:wsdl/HelloWorldWSService.wsdl",
                  targetNamespace = "http://soap.leonis.md/")
public class HelloWorldWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.leonis.md/", "HelloWorldWSService");
    public final static QName HelloWorldWSPort = new QName("http://soap.leonis.md/", "HelloWorldWSPort");
    static {
        URL url = HelloWorldWSService.class.getClassLoader().getResource("wsdl/HelloWorldWSService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(HelloWorldWSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/HelloWorldWSService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldWSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HelloWorldWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWorldWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWorldWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HelloWorldInterface
     */
    @WebEndpoint(name = "HelloWorldWSPort")
    public HelloWorldInterface getHelloWorldWSPort() {
        return super.getPort(HelloWorldWSPort, HelloWorldInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldInterface
     */
    @WebEndpoint(name = "HelloWorldWSPort")
    public HelloWorldInterface getHelloWorldWSPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldWSPort, HelloWorldInterface.class, features);
    }

}
