
package md.leonis.soap.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-18T17:10:11.080+03:00
 * Generated source version: 3.3.2
 *
 */
public final class HelloWorldInterface_HelloWorldWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.leonis.md/", "HelloWorldWSService");

    private HelloWorldInterface_HelloWorldWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWorldWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        HelloWorldWSService ss = new HelloWorldWSService(wsdlURL, SERVICE_NAME);
        HelloWorldInterface port = ss.getHelloWorldWSPort();

        {
        System.out.println("Invoking helloWorldWebMethod...");
        java.lang.String _helloWorldWebMethod_arg0 = "";
        java.lang.String _helloWorldWebMethod__return = port.helloWorldWebMethod(_helloWorldWebMethod_arg0);
        System.out.println("helloWorldWebMethod.result=" + _helloWorldWebMethod__return);


        }
        {
        System.out.println("Invoking helloWorldArrayListWebMethod...");
        java.lang.String _helloWorldArrayListWebMethod_arg0 = "";
        java.util.List<java.lang.String> _helloWorldArrayListWebMethod__return = port.helloWorldArrayListWebMethod(_helloWorldArrayListWebMethod_arg0);
        System.out.println("helloWorldArrayListWebMethod.result=" + _helloWorldArrayListWebMethod__return);


        }

        System.exit(0);
    }

}
