
package md.leonis.soap.cxf;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-18T17:10:11.160+03:00
 * Generated source version: 3.3.2
 *
 */

public class HelloWorldInterface_HelloWorldWSPort_Server{

    protected HelloWorldInterface_HelloWorldWSPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWorldWSPortImpl();
        String address = "REPLACE_WITH_ACTUAL_URL";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new HelloWorldInterface_HelloWorldWSPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
