package md.leonis.soap.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-18T17:10:11.150+03:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://soap.leonis.md/", name = "HelloWorldInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldInterface {

    @WebMethod
    @Action(input = "http://soap.leonis.md/HelloWorldInterface/helloWorldWebMethodRequest", output = "http://soap.leonis.md/HelloWorldInterface/helloWorldWebMethodResponse")
    @RequestWrapper(localName = "helloWorldWebMethod", targetNamespace = "http://soap.leonis.md/", className = "md.leonis.soap.cxf.HelloWorldWebMethod")
    @ResponseWrapper(localName = "helloWorldWebMethodResponse", targetNamespace = "http://soap.leonis.md/", className = "md.leonis.soap.cxf.HelloWorldWebMethodResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String helloWorldWebMethod(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://soap.leonis.md/HelloWorldInterface/helloWorldArrayListWebMethodRequest", output = "http://soap.leonis.md/HelloWorldInterface/helloWorldArrayListWebMethodResponse")
    @RequestWrapper(localName = "helloWorldArrayListWebMethod", targetNamespace = "http://soap.leonis.md/", className = "md.leonis.soap.cxf.HelloWorldArrayListWebMethod")
    @ResponseWrapper(localName = "helloWorldArrayListWebMethodResponse", targetNamespace = "http://soap.leonis.md/", className = "md.leonis.soap.cxf.HelloWorldArrayListWebMethodResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> helloWorldArrayListWebMethod(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
