package md.leonis.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-07-29T15:40:15.448+03:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://server.ws.leonis.md/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "updateDates", targetNamespace = "http://server.ws.leonis.md/", className = "md.leonis.ws.client.UpdateDates")
    @ResponseWrapper(localName = "updateDatesResponse", targetNamespace = "http://server.ws.leonis.md/", className = "md.leonis.ws.client.UpdateDatesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public md.leonis.ws.client.User updateDates(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Integer id,
        @WebParam(name = "dates", targetNamespace = "")
        md.leonis.ws.client.Dates dates
    );

    @WebMethod
    @RequestWrapper(localName = "addNote", targetNamespace = "http://server.ws.leonis.md/", className = "md.leonis.ws.client.AddNote")
    @ResponseWrapper(localName = "addNoteResponse", targetNamespace = "http://server.ws.leonis.md/", className = "md.leonis.ws.client.AddNoteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public md.leonis.ws.client.User addNote(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Integer id,
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "value", targetNamespace = "")
        int value
    );

    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://server.ws.leonis.md/", className = "md.leonis.ws.client.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://server.ws.leonis.md/", className = "md.leonis.ws.client.GetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public md.leonis.ws.client.User get(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Integer id
    );

    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://server.ws.leonis.md/", className = "md.leonis.ws.client.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://server.ws.leonis.md/", className = "md.leonis.ws.client.CreateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public md.leonis.ws.client.User create()
;

    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://server.ws.leonis.md/", className = "md.leonis.ws.client.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://server.ws.leonis.md/", className = "md.leonis.ws.client.SaveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public md.leonis.ws.client.User save(

        @WebParam(name = "user", targetNamespace = "")
        md.leonis.ws.client.User user
    );

    @WebMethod
    @RequestWrapper(localName = "addHobbie", targetNamespace = "http://server.ws.leonis.md/", className = "md.leonis.ws.client.AddHobbie")
    @ResponseWrapper(localName = "addHobbieResponse", targetNamespace = "http://server.ws.leonis.md/", className = "md.leonis.ws.client.AddHobbieResponse")
    @WebResult(name = "return", targetNamespace = "")
    public md.leonis.ws.client.User addHobbie(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Integer id,
        @WebParam(name = "hobbie", targetNamespace = "")
        java.lang.String hobbie
    );
}
