
package md.leonis.soap.client;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.io.File;
import java.net.URL;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * <p>
 * Modified!!!
 */
@WebServiceClient(name = "serviceName", targetNamespace = "http://soap.leonis.md/")
public class ServiceName extends Service {

    private static URL SERVICENAME_WSDL_LOCATION;
    private final static QName SERVICENAME_QNAME = new QName("http://soap.leonis.md/", "serviceName");

    public ServiceName() {
        super(getWsdlLocation(null), SERVICENAME_QNAME);
    }

    public ServiceName(String wsdlPath) {
        super(getWsdlLocation(wsdlPath), SERVICENAME_QNAME);
    }

    /**
     * @return returns HelloWorldInterface
     */
    @WebEndpoint(name = "portName")
    public HelloWorldInterface getPortName() {
        return super.getPort(new QName("http://soap.leonis.md/", "portName"), HelloWorldInterface.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns HelloWorldInterface
     */
    @WebEndpoint(name = "portName")
    public HelloWorldInterface getPortName(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.leonis.md/", "portName"), HelloWorldInterface.class, features);
    }

    private static URL getWsdlLocation(String wsdlPath) {
        if (SERVICENAME_WSDL_LOCATION != null) {
            return SERVICENAME_WSDL_LOCATION;
        }

        try {
            if (wsdlPath != null) {
                SERVICENAME_WSDL_LOCATION = new File(wsdlPath).toURI().toURL();
            } else {
                SERVICENAME_WSDL_LOCATION = ServiceName.class.getClassLoader().getResource("wsdl/ServiceName.wsdl");
            }
        } catch (Exception ex) {
            throw new WebServiceException(ex);
        }

        return SERVICENAME_WSDL_LOCATION;
    }

}
