
package md.leonis.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "serviceName", targetNamespace = "http://soap.leonis.md/", wsdlLocation = "http://localhost:8080/hello/newEndpoint?wsdl")
public class ServiceName
    extends Service
{

    private final static URL SERVICENAME_WSDL_LOCATION;
    private final static WebServiceException SERVICENAME_EXCEPTION;
    private final static QName SERVICENAME_QNAME = new QName("http://soap.leonis.md/", "serviceName");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hello/newEndpoint?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICENAME_WSDL_LOCATION = url;
        SERVICENAME_EXCEPTION = e;
    }

    public ServiceName() {
        super(__getWsdlLocation(), SERVICENAME_QNAME);
    }

    public ServiceName(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICENAME_QNAME, features);
    }

    public ServiceName(URL wsdlLocation) {
        super(wsdlLocation, SERVICENAME_QNAME);
    }

    public ServiceName(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICENAME_QNAME, features);
    }

    public ServiceName(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceName(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWorldInterface
     */
    @WebEndpoint(name = "portName")
    public HelloWorldInterface getPortName() {
        return super.getPort(new QName("http://soap.leonis.md/", "portName"), HelloWorldInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldInterface
     */
    @WebEndpoint(name = "portName")
    public HelloWorldInterface getPortName(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.leonis.md/", "portName"), HelloWorldInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICENAME_EXCEPTION!= null) {
            throw SERVICENAME_EXCEPTION;
        }
        return SERVICENAME_WSDL_LOCATION;
    }

}
